<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SurahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $surahs = [
            ['id' => 1, 'nama_latin' => 'Al-Fatihah', 'nama_arab' => 'الفاتحة', 'jumlah_ayat' => 7, 'tempat_turun' => 'Makkiyah'],
            ['id' => 2, 'nama_latin' => 'Al-Baqarah', 'nama_arab' => 'البقرة', 'jumlah_ayat' => 286, 'tempat_turun' => 'Madaniyah'],
            ['id' => 3, 'nama_latin' => 'Ali \'Imran', 'nama_arab' => 'آل عمران', 'jumlah_ayat' => 200, 'tempat_turun' => 'Madaniyah'],
            ['id' => 4, 'nama_latin' => 'An-Nisa\'', 'nama_arab' => 'النساء', 'jumlah_ayat' => 176, 'tempat_turun' => 'Madaniyah'],
            ['id' => 5, 'nama_latin' => 'Al-Ma\'idah', 'nama_arab' => 'المائدة', 'jumlah_ayat' => 120, 'tempat_turun' => 'Madaniyah'],
            ['id' => 6, 'nama_latin' => 'Al-An\'am', 'nama_arab' => 'الأنعام', 'jumlah_ayat' => 165, 'tempat_turun' => 'Makkiyah'],
            ['id' => 7, 'nama_latin' => 'Al-A\'raf', 'nama_arab' => 'الأعراف', 'jumlah_ayat' => 206, 'tempat_turun' => 'Makkiyah'],
            ['id' => 8, 'nama_latin' => 'Al-Anfal', 'nama_arab' => 'الأنفال', 'jumlah_ayat' => 75, 'tempat_turun' => 'Madaniyah'],
            ['id' => 9, 'nama_latin' => 'At-Taubah', 'nama_arab' => 'التوبة', 'jumlah_ayat' => 129, 'tempat_turun' => 'Madaniyah'],
            ['id' => 10, 'nama_latin' => 'Yunus', 'nama_arab' => 'يونس', 'jumlah_ayat' => 109, 'tempat_turun' => 'Makkiyah'],
            ['id' => 11, 'nama_latin' => 'Hud', 'nama_arab' => 'هود', 'jumlah_ayat' => 123, 'tempat_turun' => 'Makkiyah'],
            ['id' => 12, 'nama_latin' => 'Yusuf', 'nama_arab' => 'يوسف', 'jumlah_ayat' => 111, 'tempat_turun' => 'Makkiyah'],
            ['id' => 13, 'nama_latin' => 'Ar-Ra\'d', 'nama_arab' => 'الرعد', 'jumlah_ayat' => 43, 'tempat_turun' => 'Madaniyah'],
            ['id' => 14, 'nama_latin' => 'Ibrahim', 'nama_arab' => 'إبراهيم', 'jumlah_ayat' => 52, 'tempat_turun' => 'Makkiyah'],
            ['id' => 15, 'nama_latin' => 'Al-Hijr', 'nama_arab' => 'الحجر', 'jumlah_ayat' => 99, 'tempat_turun' => 'Makkiyah'],
            ['id' => 16, 'nama_latin' => 'An-Nahl', 'nama_arab' => 'النحل', 'jumlah_ayat' => 128, 'tempat_turun' => 'Makkiyah'],
            ['id' => 17, 'nama_latin' => 'Al-Isra\'', 'nama_arab' => 'الإسراء', 'jumlah_ayat' => 111, 'tempat_turun' => 'Makkiyah'],
            ['id' => 18, 'nama_latin' => 'Al-Kahf', 'nama_arab' => 'الكهف', 'jumlah_ayat' => 110, 'tempat_turun' => 'Makkiyah'],
            ['id' => 19, 'nama_latin' => 'Maryam', 'nama_arab' => 'مريم', 'jumlah_ayat' => 98, 'tempat_turun' => 'Makkiyah'],
            ['id' => 20, 'nama_latin' => 'Ta Ha', 'nama_arab' => 'طه', 'jumlah_ayat' => 135, 'tempat_turun' => 'Makkiyah'],
            ['id' => 21, 'nama_latin' => 'Al-Anbiya\'', 'nama_arab' => 'الأنبياء', 'jumlah_ayat' => 112, 'tempat_turun' => 'Makkiyah'],
            ['id' => 22, 'nama_latin' => 'Al-Hajj', 'nama_arab' => 'الحج', 'jumlah_ayat' => 78, 'tempat_turun' => 'Madaniyah'],
            ['id' => 23, 'nama_latin' => 'Al-Mu\'minun', 'nama_arab' => 'المؤمنون', 'jumlah_ayat' => 118, 'tempat_turun' => 'Makkiyah'],
            ['id' => 24, 'nama_latin' => 'An-Nur', 'nama_arab' => 'النور', 'jumlah_ayat' => 64, 'tempat_turun' => 'Madaniyah'],
            ['id' => 25, 'nama_latin' => 'Al-Furqan', 'nama_arab' => 'الفرقان', 'jumlah_ayat' => 77, 'tempat_turun' => 'Makkiyah'],
            ['id' => 26, 'nama_latin' => 'Asy-Syu\'ara\'', 'nama_arab' => 'الشعراء', 'jumlah_ayat' => 227, 'tempat_turun' => 'Makkiyah'],
            ['id' => 27, 'nama_latin' => 'An-Naml', 'nama_arab' => 'النمل', 'jumlah_ayat' => 93, 'tempat_turun' => 'Makkiyah'],
            ['id' => 28, 'nama_latin' => 'Al-Qasas', 'nama_arab' => 'القصص', 'jumlah_ayat' => 88, 'tempat_turun' => 'Makkiyah'],
            ['id' => 29, 'nama_latin' => 'Al-\'Ankabut', 'nama_arab' => 'العنكبوت', 'jumlah_ayat' => 69, 'tempat_turun' => 'Makkiyah'],
            ['id' => 30, 'nama_latin' => 'Ar-Rum', 'nama_arab' => 'الروم', 'jumlah_ayat' => 60, 'tempat_turun' => 'Makkiyah'],
            ['id' => 31, 'nama_latin' => 'Luqman', 'nama_arab' => 'لقمان', 'jumlah_ayat' => 34, 'tempat_turun' => 'Makkiyah'],
            ['id' => 32, 'nama_latin' => 'As-Sajdah', 'nama_arab' => 'السجدة', 'jumlah_ayat' => 30, 'tempat_turun' => 'Makkiyah'],
            ['id' => 33, 'nama_latin' => 'Al-Ahzab', 'nama_arab' => 'الأحزاب', 'jumlah_ayat' => 73, 'tempat_turun' => 'Madaniyah'],
            ['id' => 34, 'nama_latin' => 'Saba\'', 'nama_arab' => 'سبأ', 'jumlah_ayat' => 54, 'tempat_turun' => 'Makkiyah'],
            ['id' => 35, 'nama_latin' => 'Fatir', 'nama_arab' => 'فاطر', 'jumlah_ayat' => 45, 'tempat_turun' => 'Makkiyah'],
            ['id' => 36, 'nama_latin' => 'Ya Sin', 'nama_arab' => 'يس', 'jumlah_ayat' => 83, 'tempat_turun' => 'Makkiyah'],
            ['id' => 37, 'nama_latin' => 'As-Saffat', 'nama_arab' => 'الصافات', 'jumlah_ayat' => 182, 'tempat_turun' => 'Makkiyah'],
            ['id' => 38, 'nama_latin' => 'Sad', 'nama_arab' => 'ص', 'jumlah_ayat' => 88, 'tempat_turun' => 'Makkiyah'],
            ['id' => 39, 'nama_latin' => 'Az-Zumar', 'nama_arab' => 'الزمر', 'jumlah_ayat' => 75, 'tempat_turun' => 'Makkiyah'],
            ['id' => 40, 'nama_latin' => 'Ghafir', 'nama_arab' => 'غافر', 'jumlah_ayat' => 85, 'tempat_turun' => 'Makkiyah'],
            ['id' => 41, 'nama_latin' => 'Fussilat', 'nama_arab' => 'فصلت', 'jumlah_ayat' => 54, 'tempat_turun' => 'Makkiyah'],
            ['id' => 42, 'nama_latin' => 'Asy-Syura', 'nama_arab' => 'الشورى', 'jumlah_ayat' => 53, 'tempat_turun' => 'Makkiyah'],
            ['id' => 43, 'nama_latin' => 'Az-Zukhruf', 'nama_arab' => 'الزخرف', 'jumlah_ayat' => 89, 'tempat_turun' => 'Makkiyah'],
            ['id' => 44, 'nama_latin' => 'Ad-Dukhan', 'nama_arab' => 'الدخان', 'jumlah_ayat' => 59, 'tempat_turun' => 'Makkiyah'],
            ['id' => 45, 'nama_latin' => 'Al-Jasiyah', 'nama_arab' => 'الجاثية', 'jumlah_ayat' => 37, 'tempat_turun' => 'Makkiyah'],
            ['id' => 46, 'nama_latin' => 'Al-Ahqaf', 'nama_arab' => 'الأحقاف', 'jumlah_ayat' => 35, 'tempat_turun' => 'Makkiyah'],
            ['id' => 47, 'nama_latin' => 'Muhammad', 'nama_arab' => 'محمد', 'jumlah_ayat' => 38, 'tempat_turun' => 'Madaniyah'],
            ['id' => 48, 'nama_latin' => 'Al-Fath', 'nama_arab' => 'الفتح', 'jumlah_ayat' => 29, 'tempat_turun' => 'Madaniyah'],
            ['id' => 49, 'nama_latin' => 'Al-Hujurat', 'nama_arab' => 'الحجرات', 'jumlah_ayat' => 18, 'tempat_turun' => 'Madaniyah'],
            ['id' => 50, 'nama_latin' => 'Qaf', 'nama_arab' => 'ق', 'jumlah_ayat' => 45, 'tempat_turun' => 'Makkiyah'],
            ['id' => 51, 'nama_latin' => 'Az-Zariyat', 'nama_arab' => 'الذاريات', 'jumlah_ayat' => 60, 'tempat_turun' => 'Makkiyah'],
            ['id' => 52, 'nama_latin' => 'At-Tur', 'nama_arab' => 'الطور', 'jumlah_ayat' => 49, 'tempat_turun' => 'Makkiyah'],
            ['id' => 53, 'nama_latin' => 'An-Najm', 'nama_arab' => 'النجم', 'jumlah_ayat' => 62, 'tempat_turun' => 'Makkiyah'],
            ['id' => 54, 'nama_latin' => 'Al-Qamar', 'nama_arab' => 'القمر', 'jumlah_ayat' => 55, 'tempat_turun' => 'Makkiyah'],
            ['id' => 55, 'nama_latin' => 'Ar-Rahman', 'nama_arab' => 'الرحمن', 'jumlah_ayat' => 78, 'tempat_turun' => 'Madaniyah'],
            ['id' => 56, 'nama_latin' => 'Al-Waqi\'ah', 'nama_arab' => 'الواقعة', 'jumlah_ayat' => 96, 'tempat_turun' => 'Makkiyah'],
            ['id' => 57, 'nama_latin' => 'Al-Hadid', 'nama_arab' => 'الحديد', 'jumlah_ayat' => 29, 'tempat_turun' => 'Madaniyah'],
            ['id' => 58, 'nama_latin' => 'Al-Mujadilah', 'nama_arab' => 'المجادلة', 'jumlah_ayat' => 22, 'tempat_turun' => 'Madaniyah'],
            ['id' => 59, 'nama_latin' => 'Al-Hasyr', 'nama_arab' => 'الحشر', 'jumlah_ayat' => 24, 'tempat_turun' => 'Madaniyah'],
            ['id' => 60, 'nama_latin' => 'Al-Mumtahanah', 'nama_arab' => 'الممتحنة', 'jumlah_ayat' => 13, 'tempat_turun' => 'Madaniyah'],
            ['id' => 61, 'nama_latin' => 'As-Saff', 'nama_arab' => 'الصف', 'jumlah_ayat' => 14, 'tempat_turun' => 'Madaniyah'],
            ['id' => 62, 'nama_latin' => 'Al-Jumu\'ah', 'nama_arab' => 'الجمعة', 'jumlah_ayat' => 11, 'tempat_turun' => 'Madaniyah'],
            ['id' => 63, 'nama_latin' => 'Al-Munafiqun', 'nama_arab' => 'المنافقون', 'jumlah_ayat' => 11, 'tempat_turun' => 'Madaniyah'],
            ['id' => 64, 'nama_latin' => 'At-Tagabun', 'nama_arab' => 'التغابن', 'jumlah_ayat' => 18, 'tempat_turun' => 'Madaniyah'],
            ['id' => 65, 'nama_latin' => 'At-Talaq', 'nama_arab' => 'الطلاق', 'jumlah_ayat' => 12, 'tempat_turun' => 'Madaniyah'],
            ['id' => 66, 'nama_latin' => 'At-Tahrim', 'nama_arab' => 'التحريم', 'jumlah_ayat' => 12, 'tempat_turun' => 'Madaniyah'],
            ['id' => 67, 'nama_latin' => 'Al-Mulk', 'nama_arab' => 'الملك', 'jumlah_ayat' => 30, 'tempat_turun' => 'Makkiyah'],
            ['id' => 68, 'nama_latin' => 'Al-Qalam', 'nama_arab' => 'القلم', 'jumlah_ayat' => 52, 'tempat_turun' => 'Makkiyah'],
            ['id' => 69, 'nama_latin' => 'Al-Haqqah', 'nama_arab' => 'الحاقة', 'jumlah_ayat' => 52, 'tempat_turun' => 'Makkiyah'],
            ['id' => 70, 'nama_latin' => 'Al-Ma\'arij', 'nama_arab' => 'المعارج', 'jumlah_ayat' => 44, 'tempat_turun' => 'Makkiyah'],
            ['id' => 71, 'nama_latin' => 'Nuh', 'nama_arab' => 'نوح', 'jumlah_ayat' => 28, 'tempat_turun' => 'Makkiyah'],
            ['id' => 72, 'nama_latin' => 'Al-Jinn', 'nama_arab' => 'الجن', 'jumlah_ayat' => 28, 'tempat_turun' => 'Makkiyah'],
            ['id' => 73, 'nama_latin' => 'Al-Muzzammil', 'nama_arab' => 'المزمل', 'jumlah_ayat' => 20, 'tempat_turun' => 'Makkiyah'],
            ['id' => 74, 'nama_latin' => 'Al-Muddassir', 'nama_arab' => 'المدثر', 'jumlah_ayat' => 56, 'tempat_turun' => 'Makkiyah'],
            ['id' => 75, 'nama_latin' => 'Al-Qiyamah', 'nama_arab' => 'القيامة', 'jumlah_ayat' => 40, 'tempat_turun' => 'Makkiyah'],
            ['id' => 76, 'nama_latin' => 'Al-Insan', 'nama_arab' => 'الإنسان', 'jumlah_ayat' => 31, 'tempat_turun' => 'Madaniyah'],
            ['id' => 77, 'nama_latin' => 'Al-Mursalat', 'nama_arab' => 'المرسلات', 'jumlah_ayat' => 50, 'tempat_turun' => 'Makkiyah'],
            ['id' => 78, 'nama_latin' => 'An-Naba\'', 'nama_arab' => 'النبأ', 'jumlah_ayat' => 40, 'tempat_turun' => 'Makkiyah'],
            ['id' => 79, 'nama_latin' => 'An-Nazi\'at', 'nama_arab' => 'النازعات', 'jumlah_ayat' => 46, 'tempat_turun' => 'Makkiyah'],
            ['id' => 80, 'nama_latin' => 'Abasa', 'nama_arab' => 'عبس', 'jumlah_ayat' => 42, 'tempat_turun' => 'Makkiyah'],
            ['id' => 81, 'nama_latin' => 'At-Takwir', 'nama_arab' => 'التكوير', 'jumlah_ayat' => 29, 'tempat_turun' => 'Makkiyah'],
            ['id' => 82, 'nama_latin' => 'Al-Infitar', 'nama_arab' => 'الانفطار', 'jumlah_ayat' => 19, 'tempat_turun' => 'Makkiyah'],
            ['id' => 83, 'nama_latin' => 'Al-Mutaffifin', 'nama_arab' => 'المطففين', 'jumlah_ayat' => 36, 'tempat_turun' => 'Makkiyah'],
            ['id' => 84, 'nama_latin' => 'Al-Insyiqaq', 'nama_arab' => 'الانشقاق', 'jumlah_ayat' => 25, 'tempat_turun' => 'Makkiyah'],
            ['id' => 85, 'nama_latin' => 'Al-Buruj', 'nama_arab' => 'البروج', 'jumlah_ayat' => 22, 'tempat_turun' => 'Makkiyah'],
            ['id' => 86, 'nama_latin' => 'At-Tariq', 'nama_arab' => 'الطارق', 'jumlah_ayat' => 17, 'tempat_turun' => 'Makkiyah'],
            ['id' => 87, 'nama_latin' => 'Al-A\'la', 'nama_arab' => 'الأعلى', 'jumlah_ayat' => 19, 'tempat_turun' => 'Makkiyah'],
            ['id' => 88, 'nama_latin' => 'Al-Gasyiyah', 'nama_arab' => 'الغاشية', 'jumlah_ayat' => 26, 'tempat_turun' => 'Makkiyah'],
            ['id' => 89, 'nama_latin' => 'Al-Fajr', 'nama_arab' => 'الفجر', 'jumlah_ayat' => 30, 'tempat_turun' => 'Makkiyah'],
            ['id' => 90, 'nama_latin' => 'Al-Balad', 'nama_arab' => 'البلد', 'jumlah_ayat' => 20, 'tempat_turun' => 'Makkiyah'],
            ['id' => 91, 'nama_latin' => 'Asy-Syams', 'nama_arab' => 'الشمس', 'jumlah_ayat' => 15, 'tempat_turun' => 'Makkiyah'],
            ['id' => 92, 'nama_latin' => 'Al-Lail', 'nama_arab' => 'الليل', 'jumlah_ayat' => 21, 'tempat_turun' => 'Makkiyah'],
            ['id' => 93, 'nama_latin' => 'Ad-Duha', 'nama_arab' => 'الضحى', 'jumlah_ayat' => 11, 'tempat_turun' => 'Makkiyah'],
            ['id' => 94, 'nama_latin' => 'Asy-Syarh', 'nama_arab' => 'الشرح', 'jumlah_ayat' => 8, 'tempat_turun' => 'Makkiyah'],
            ['id' => 95, 'nama_latin' => 'At-Tin', 'nama_arab' => 'التين', 'jumlah_ayat' => 8, 'tempat_turun' => 'Makkiyah'],
            ['id' => 96, 'nama_latin' => 'Al-\'Alaq', 'nama_arab' => 'العلق', 'jumlah_ayat' => 19, 'tempat_turun' => 'Makkiyah'],
            ['id' => 97, 'nama_latin' => 'Al-Qadr', 'nama_arab' => 'القدر', 'jumlah_ayat' => 5, 'tempat_turun' => 'Makkiyah'],
            ['id' => 98, 'nama_latin' => 'Al-Bayyinah', 'nama_arab' => 'البينة', 'jumlah_ayat' => 8, 'tempat_turun' => 'Madaniyah'],
            ['id' => 99, 'nama_latin' => 'Az-Zalzalah', 'nama_arab' => 'الزلزلة', 'jumlah_ayat' => 8, 'tempat_turun' => 'Madaniyah'],
            ['id' => 100, 'nama_latin' => 'Al-\'Adiyat', 'nama_arab' => 'العاديات', 'jumlah_ayat' => 11, 'tempat_turun' => 'Makkiyah'],
            ['id' => 101, 'nama_latin' => 'Al-Qari\'ah', 'nama_arab' => 'القارعة', 'jumlah_ayat' => 11, 'tempat_turun' => 'Makkiyah'],
            ['id' => 102, 'nama_latin' => 'At-Takasur', 'nama_arab' => 'التكاثر', 'jumlah_ayat' => 8, 'tempat_turun' => 'Makkiyah'],
            ['id' => 103, 'nama_latin' => 'Al-\'Asr', 'nama_arab' => 'العصر', 'jumlah_ayat' => 3, 'tempat_turun' => 'Makkiyah'],
            ['id' => 104, 'nama_latin' => 'Al-Humazah', 'nama_arab' => 'الهمزة', 'jumlah_ayat' => 9, 'tempat_turun' => 'Makkiyah'],
            ['id' => 105, 'nama_latin' => 'Al-Fil', 'nama_arab' => 'الفيل', 'jumlah_ayat' => 5, 'tempat_turun' => 'Makkiyah'],
            ['id' => 106, 'nama_latin' => 'Quraisy', 'nama_arab' => 'قريش', 'jumlah_ayat' => 4, 'tempat_turun' => 'Makkiyah'],
            ['id' => 107, 'nama_latin' => 'Al-Ma\'un', 'nama_arab' => 'الماعون', 'jumlah_ayat' => 7, 'tempat_turun' => 'Makkiyah'],
            ['id' => 108, 'nama_latin' => 'Al-Kausar', 'nama_arab' => 'الكوثر', 'jumlah_ayat' => 3, 'tempat_turun' => 'Makkiyah'],
            ['id' => 109, 'nama_latin' => 'Al-Kafirun', 'nama_arab' => 'الكافرون', 'jumlah_ayat' => 6, 'tempat_turun' => 'Makkiyah'],
            ['id' => 110, 'nama_latin' => 'An-Nasr', 'nama_arab' => 'النصر', 'jumlah_ayat' => 3, 'tempat_turun' => 'Madaniyah'],
            ['id' => 111, 'nama_latin' => 'Al-Lahab', 'nama_arab' => 'المسد', 'jumlah_ayat' => 5, 'tempat_turun' => 'Makkiyah'],
            ['id' => 112, 'nama_latin' => 'Al-Ikhlas', 'nama_arab' => 'الإخلاص', 'jumlah_ayat' => 4, 'tempat_turun' => 'Makkiyah'],
            ['id' => 113, 'nama_latin' => 'Al-Falaq', 'nama_arab' => 'الفلق', 'jumlah_ayat' => 5, 'tempat_turun' => 'Makkiyah'],
            ['id' => 114, 'nama_latin' => 'An-Nas', 'nama_arab' => 'الناس', 'jumlah_ayat' => 6, 'tempat_turun' => 'Makkiyah'],
        ];

        DB::table('surahs')->insert($surahs);
    }
}
